document.writeln('<div class="modal fade" id="coopModals" role="dialog" aria-labelledby="exampleModalLabel" data-backdrop="static" data-keyboard="false" aria-hidden="true">');
  document.writeln('  <div class="modal-dialog" role="document" style="margin-top: 278px">');
    document.writeln('        <div class="modal-content">');
        document.writeln('           <div class="modal-header">');
            document.writeln('               <h5 class="modal-title">导入图片</h5>');
                document.writeln('               <button type="button" class="close" data-dismiss="modal" aria-label="Close">');
                document.writeln('                   <span aria-hidden="true">&times;</span>');
                    document.writeln('                </button>');
                document.writeln('            </div>');
            document.writeln('           <div class="modal-body">');
            document.writeln('               <div>');
                document.writeln('                   <div class="form-group">');
                    document.writeln('                       <label class="col-form-label" style="font-size: 16px;">导入图片类型</label>');
                        document.writeln('                        <input >');
    document.writeln('                     <label class="col-form-label" style="font-size: 16px;">导入图片类型</label>');
    document.writeln('                   <input >');
    document.writeln('                   <button type="button" class="btn btn-primary" id="coopSureBut">确 定</button>');
    document.writeln('    </div>');
    document.writeln('    </div>');
    document.writeln('    </div>');
    document.writeln('    </div>');
    document.writeln('    </div>');
    document.writeln('    </div>');